//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_EMPLOYEES
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string name { get; set; }
        public string last_name { get; set; }
        public string user_na { get; set; }
        public string password { get; set; }
    }
}
